name: CI

permissions:
  contents: read
  actions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'workflow_dispatch' && inputs.run-id  || github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      run-id:
        type: string
        description: The workflow ID to download artifacts (skips the build step)
  pull_request:
    paths-ignore:
      - .vscode/**/*
      - docs/**/*
      - examples/**/*
  push:
    branches:
      - main
    paths-ignore:
      - .vscode/**/*
      - docs/**/*
      - examples/**/*

jobs:
  format:
    if: ${{ !inputs.run-id }}
    name: Format
    uses: ./.github/workflows/run-format.yml
    secrets: inherit
    with:
      zig-version: 0.13.0
    permissions:
      contents: write
  lint:
    if: ${{ !inputs.run-id }}
    name: Lint
    uses: ./.github/workflows/run-lint.yml
    secrets: inherit
  windows-x64:
    if: ${{ !inputs.run-id }}
    name: Build windows-x64
    uses: ./.github/workflows/build-windows.yml
    secrets: inherit
    with:
      runs-on: windows
      tag: windows-x64
      arch: x64
      cpu: haswell
      canary: true
  windows-x64-baseline:
    if: ${{ !inputs.run-id }}
    name: Build windows-x64-baseline
    uses: ./.github/workflows/build-windows.yml
    secrets: inherit
    with:
      runs-on: windows
      tag: windows-x64-baseline
      arch: x64
      cpu: nehalem
      canary: true
  windows-x64-test:
    if: ${{ inputs.run-id || github.event_name == 'pull_request' }}
    name: Test windows-x64
    needs: windows-x64
    uses: ./.github/workflows/run-test.yml
    secrets: inherit
    with:
      run-id: ${{ inputs.run-id }}
      pr-number: ${{ github.event.number }}
      runs-on: windows
      tag: windows-x64
  windows-x64-baseline-test:
    if: ${{ inputs.run-id || github.event_name == 'pull_request' }}
    name: Test windows-x64-baseline
    needs: windows-x64-baseline
    uses: ./.github/workflows/run-test.yml
    secrets: inherit
    with:
      run-id: ${{ inputs.run-id }}
      pr-number: ${{ github.event.number }}
      runs-on: windows
      tag: windows-x64-baseline
  cleanup:
    if: ${{ always() }}
    name: Cleanup
    needs:
      - windows-x64
      - windows-x64-baseline
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup Artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            bun-*-cpp
            bun-*-zig
            bun-*-deps
            bun-*-codegen
